name: thekingcoffee
description: The King Coffee.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 0.1.3
  flutter_svg: 0.17.4
  image_picker: 0.6.7+4
  intro_slider: 2.3.1
  barcode_flutter: 1.1.2
  carousel_slider: 2.2.1
  cached_network_image: 2.2.0+1
  url_launcher: 5.5.0
  oktoast: 2.3.2
  http: 0.12.1
  shared_preferences: 0.5.8
  datetime_picker_formfield: 1.0.0
  flutter_slidable: 0.5.4
  location: 3.0.2
  geocoder: 0.2.1
  google_maps_flutter: 0.5.28+1
  firebase_auth: 0.16.1
  firebase_core: 0.4.5
  flutter_webview_plugin: 0.3.11
  provider: 4.3.0
 


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  
  assets:
   - assets/images/
   - assets/icons/
   - assets/i18n/


  fonts:
   - family: BalooBhai-Regular
     fonts:
      - asset: assets/fonts/BalooBhai-Regular.ttf
   - family: SFUIText-Medium
     fonts:
      - asset: assets/fonts/SFUIText-Medium.ttf
   - family: SFUIText-Regular
     fonts:
      - asset: assets/fonts/SFUIText-Regular.ttf
   - family: VarelaRound-Regular
     fonts:
      - asset: assets/fonts/VarelaRound-Regular.ttf
   - family: Raleway-Bold
     fonts:
      - asset: assets/fonts/Raleway-Bold.ttf
   - family: Raleway-Regular
     fonts:
      - asset: assets/fonts/Raleway-Regular.ttf
   - family: RobotoMono-Bold
     fonts:
      - asset: assets/fonts/RobotoMono-Bold.ttf
   - family: RobotoMono-Regular
     fonts:
      - asset: assets/fonts/RobotoMono-Regular.ttf








