name: thekingcoffee
description: The King Coffee.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.14.0
  image_picker: 0.5.3
  intro_slider: 1.2.0
  barcode_flutter: 1.0.0
  carousel_slider: 1.3.0
  cached_network_image: ^1.1.1
  url_launcher: 5.0.3
  fluttertoast: 3.0.4
  bloc: 0.12.0
  flutter_bloc: 0.11.1
  http: 0.12.0
  shared_preferences: 0.5.2
  datetime_picker_formfield: 0.1.8
  flutter_slidable: 0.4.7
  location: 2.3.5
  geocoder: 0.1.2
  google_maps_flutter: 0.5.15
 


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  uses-material-design: true

  
  assets:
   - assets/images/
   - assets/icons/
   - assets/i18n/


  fonts:
   - family: BalooBhai-Regular
     fonts:
      - asset: assets/fonts/BalooBhai-Regular.ttf
   - family: SFUIText-Medium
     fonts:
      - asset: assets/fonts/SFUIText-Medium.ttf
   - family: SFUIText-Regular
     fonts:
      - asset: assets/fonts/SFUIText-Regular.ttf
   - family: VarelaRound-Regular
     fonts:
      - asset: assets/fonts/VarelaRound-Regular.ttf
   - family: Raleway-Bold
     fonts:
      - asset: assets/fonts/Raleway-Bold.ttf
   - family: Raleway-Regular
     fonts:
      - asset: assets/fonts/Raleway-Regular.ttf
   - family: RobotoMono-Bold
     fonts:
      - asset: assets/fonts/RobotoMono-Bold.ttf
   - family: RobotoMono-Regular
     fonts:
      - asset: assets/fonts/RobotoMono-Regular.ttf








